export const AIRTABLE_TABLES = {
  USERS: "Users",
  RESUMES: "Resumes",
  EDUCATIONS: "Educations",
  WORKS: "Works",
  LOOKUPS: "Lookups",
} as const;

export const AIRTABLE_FIELDS = {
  [AIRTABLE_TABLES.USERS]: {
    id: "id",
    anonKey: "anon_key",
    createdAt: "created_at",
    updatedAt: "updated_at",
    sourceEnv: "source_env",
    prRef: "pr_ref",
  },
  [AIRTABLE_TABLES.RESUMES]: {
    id: "id",
    userId: "user_id",
    lastNameKanji: "last_name_kanji",
    firstNameKanji: "first_name_kanji",
    dobYear: "dob_year",
    dobMonth: "dob_month",
    dobDay: "dob_day",
    gender: "gender",
    schoolStatus: "school_status",
    desiredStartWhen: "desired_start_when",
    jobChangeCount: "job_change_count",
    highestEducation: "highest_education",
    desiredLocations: "desired_locations",
    desiredRoles: "desired_roles",
    desiredIndustries: "desired_industries",
    selfprDraft: "selfpr_draft",
    selfprFinal: "selfpr_final",
    summaryDraft: "summary_draft",
    summaryFinal: "summary_final",
    pdfUrl: "pdf_url",
    stepCompleted: "step_completed",
    createdAt: "created_at",
    updatedAt: "updated_at",
    sourceEnv: "source_env",
    prRef: "pr_ref",
  },
  [AIRTABLE_TABLES.EDUCATIONS]: {
    id: "id",
    resumeId: "resume_id",
    schoolName: "school_name",
    faculty: "faculty",
    department: "department",
    admissionYear: "admission_year",
    graduationYear: "graduation_year",
    createdAt: "created_at",
    updatedAt: "updated_at",
    sourceEnv: "source_env",
    prRef: "pr_ref",
  },
  [AIRTABLE_TABLES.WORKS]: {
    id: "id",
    resumeId: "resume_id",
    company: "company",
    division: "division",
    title: "title",
    startYm: "start_ym",
    endYm: "end_ym",
    roles: "roles",
    industries: "industries",
    toolsText: "tools_text",
    qJobDesc: "q_job_desc",
    qTools: "q_tools",
    qTasks: "q_tasks",
    qProblem: "q_problem",
    qAction: "q_action",
    qResult: "q_result",
    qualifications: "qualifications",
    createdAt: "created_at",
    updatedAt: "updated_at",
    sourceEnv: "source_env",
    prRef: "pr_ref",
  },
  [AIRTABLE_TABLES.LOOKUPS]: {
    id: "id",
    group: "group",
    value: "value",
    order: "order",
    isActive: "is_active",
    createdAt: "created_at",
    updatedAt: "updated_at",
    sourceEnv: "source_env",
    prRef: "pr_ref",
  },
} as const;

export const FIELD_MAPPING = AIRTABLE_FIELDS;

export type AirtableTableName = (typeof AIRTABLE_TABLES)[keyof typeof AIRTABLE_TABLES];
